### ISSUE TITLE
RowExistUser Problem beim Auslesen

### ISSUE THREAD

**Issue by Pillowg1rl** [kevgk/Autohotkey-MySQL-Api#16]
`Benutzername_Eingabe = Max.Mustermann`
`
RowExistUser := leya.rowExist("Mitarbeiter", Benutzername_Eingabe)`
`RowExistUser1 := RowExistUser.Data`
`msgbox % RoxExistUser`

Bekomme hier die Rückmeldung im Debug `ï»¿<!--response="{"data":1,"error":0,"affectedRows":1}"-->`
Mache ich beim auslesen irgendwas falsch ?

**Comment by kevgk** [comment]
`msgbox % RowExistUser1` sollte dir `1` geben, wenn die Row existiert und `0` wenn nicht.

**Comment by Pillowg1rl** [comment]
Ah... hatte die 1 bei der `msgbox ` vergessen xD
