### ISSUE TITLE
Frage zu "getwhere"

### ISSUE THREAD

**Issue by Pillowg1rl** [kevgk/Autohotkey-MySQL-Api#18]
Das Schreiben vom Befehl bekomme ich so hin. Probleme macht mir aktuell nur das Auslesen..
Script: `Kunden_Liste_Readout := leya.listRows(TabelleReadout) ; Reads out of MYSQL`
Rückmeldung Debug: `ï»¿<!--response="{"data":["Wert1","Wert2","Wert3"],"error":0,"affectedRows":3}"-->`
Da ist ja klar, dass man dann `Kunden_Liste_Readout.Data[1]` den entsprechenden Wert bekommt.

Aber wie ist das bei getwhere ?
`leya.getwhere("Help","HelpPunkt","Helpkategorie","=",BenutzerWahlHelpDDL)` (BenutzerWahlHelpDDL ist z.B. Login oder Programm)
Rückmeldung Debug: `ï»¿<!--response="{"data":[{"HelpPunkt":"test"},{"HelpPunkt":"test2"}],"error":0,"affectedRows":2}"-->`

Leider bekomme ich mit `Readout.Data.HelpPunkt[1]` noch ohne das HelpPunkt (`Readout.Data[1]`) die Werte ausgelesen... wo liegt mein Fehler ?

**Comment by kevgk** [comment]
`Readout.data[1].HelpPunkt` sollte funktionieren.

**Comment by Pillowg1rl** [comment]
Top. hat funktioniert. danke
