### ISSUE TITLE
Update hash Algorithmus

### ISSUE THREAD

**Issue by Pillowg1rl** [kevgk/Autohotkey-MySQL-Api#21]
Hey.

MD5 ist leider nicht mehr so wirklich sicher... Wäre es Möglich, den Algorithmus zu einem moderneren upzugraden ? :)
lg Michelle

**Comment by kevgk** [comment]
Hash nimmt als zweiten Parameter den Namen eines Hashing-Algorithmus und nutzt md5, falls kein zweiter Parameter angegeben wurde.

Das heißt du kannst jeden Hashing-Algorithmus nutzen, den dein Server unterstützt, die API nutzt die PHP hash_algos Funktion um zu testen, ob dein angegebener Hashing-Algorithmus vom Server unterstützt wird.

Hier findest du eine Liste von Algorithmen, die dein Server unterstützen sollte, https://www.php.net/manual/de/function.hash-algos.php.
